# Snort Configuration (Simplified for SOC Lab)

include /etc/snort/rules/local.rules

var HOME_NET any
var EXTERNAL_NET any

preprocessor stream5_global: track_tcp yes, track_udp yes
preprocessor stream5_tcp: policy linux, detect_anomalies
preprocessor http_inspect: global iis_unicode_map unicode.map 1252

output alert_fast: stdout
