# TheHive Configuration (Simplified for SOC Lab)

play.http.secret.key = "changeme"

thehive {
  db {
    provider = elasticsearch
    host = "http://thehive-elasticsearch:9201"
  }

  cortex {
    servers = [
      {
        name = "cortex"
        url = "http://cortex:9001"
        auth {
          type = "none"
        }
      }
    ]
  }
}
